// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// DocumentController is an autogenerated mock type for the DocumentController type
type DocumentController struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *DocumentController) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// List provides a mock function with given fields: w, r
func (_m *DocumentController) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
